name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish
    runs-on: yc-arc
    env:
      OWNER: mechta-market
      IMAGE: pytest:latest
    steps:
      - uses: actions/checkout@v5

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker build -t ghcr.io/$OWNER/$IMAGE .

      - run: docker push ghcr.io/$OWNER/$IMAGE
